sudo: required
services:
- docker

env:
  global:
  - DOCKER_REPO=ubuntu
  - secure: "FkyBotzqHDBZGAvmgZ5D29nBVPUHYoVb4sz7nKtRFmTYoUDizedRgSU68AI87IsQCe50kilusilYSH0sufRvhWEOcGmHSvbpJ1OTdvudkhiIqecfxXZTBe0vL0GrsT73E3EDJfXoE8LNZIjr99dRpH2FJUhuJg8Yoqu8p4h78Js="
  matrix:
  - VARIANT=bionic-amd64
  - VARIANT=bionic-arm64
  - VARIANT=bionic-armhf
  - VARIANT=bionic-i386
  - VARIANT=bionic-ppc64el
  - VARIANT=bionic-s390x
  - VARIANT=eoan-amd64
  - VARIANT=eoan-arm64
  - VARIANT=eoan-armhf
  - VARIANT=eoan-i386
  - VARIANT=eoan-ppc64el
  - VARIANT=eoan-s390x
  - VARIANT=focal-amd64
  - VARIANT=focal-arm64
  - VARIANT=focal-armhf
  - VARIANT=focal-ppc64el
  - VARIANT=focal-s390x
  - VARIANT=groovy-amd64
  - VARIANT=groovy-arm64
  - VARIANT=groovy-armhf
  - VARIANT=groovy-ppc64el
  - VARIANT=groovy-s390x
  - VARIANT=trusty-amd64
  - VARIANT=trusty-arm64
  - VARIANT=trusty-armhf
  - VARIANT=trusty-i386
  - VARIANT=trusty-ppc64el
  - VARIANT=xenial-amd64
  - VARIANT=xenial-arm64
  - VARIANT=xenial-armhf
  - VARIANT=xenial-i386
  - VARIANT=xenial-ppc64el
  - VARIANT=xenial-s390x

matrix:
  fast_finish: true
  allow_failures:
  # https://github.com/vicamo/docker-brew-ubuntu-core/issues/25
  - env: VARIANT=focal-s390x

branches:
  only:
  - master

before_install:
- docker run --rm --privileged vicamo/binfmt-qemu:bionic
- cat /proc/sys/fs/binfmt_misc/qemu-*

script:
- echo "${DOCKER_USER}/${DOCKER_REPO}" > repo
- make V=1 -j $(nproc) $VARIANT
- docker images | grep ^${DOCKER_USER}/${DOCKER_REPO} | awk '{print $1 ":" $2}'

after_success:
- if [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
    docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}";
    for image in $(docker images | grep ^${DOCKER_USER}/${DOCKER_REPO} | awk '{print $1 ":" $2}'); do
      docker push $image;
    done
  fi
